spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.58:3306/sxw_cms?useunicode=true&useSSL=false&characterEncoding=utf8
    username: db_whh
    password: db_whh
