## MongoDB Configuration for exam
spring:
  data:
    mongodb:
      uri: mongodb://sxw_score:sxw.score@192.168.2.28:27017/admin?socketTimeoutMS=6000000&maxPoolSize=1000
      database: sxw_score_20180510